version: '3.8'

services:
  web:
    build: .
    command: python3.10 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./.:/usr/src/veille_tracking/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    env_file:
      - ./.env
volumes:
  postgres_data:
