# Generated by Django 4.0.3 on 2023-05-08 19:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(
                    max_length=255,
                    verbose_name='titre du commentaire')),
                ('notation', models.IntegerField(
                    default=5,
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(5)])),
                ('commentary', models.TextField(verbose_name='commentaire')),
                ('book', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='app_books.book')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
