# Generated by Django 5.0.7 on 2024-07-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_publied",
            field=models.BooleanField(default=False),
        ),
    ]
