# Generated by Django 4.0.3 on 2022-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0003_alter_edition_options_edition_name_edition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Editeur'),
        ),
    ]
