# Generated by Django 5.0.7 on 2024-07-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_books", "0003_book_is_approved_book_submitted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="is_publied",
        ),
    ]
