# Generated by Django 4.0.3 on 2022-07-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0004_alter_edition_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégories'},
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
