# Generated by Django 4.0.3 on 2022-07-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0006_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livre'},
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_books.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='app_books.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='count_pages',
            field=models.IntegerField(default=0, verbose_name='Nombre de pages'),
        ),
        migrations.AddField(
            model_name='book',
            name='couverture',
            field=models.ImageField(default='', upload_to='', verbose_name='Couverture'),
        ),
        migrations.AddField(
            model_name='book',
            name='current_pages',
            field=models.IntegerField(default=0, verbose_name='Page Courante'),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_books.edition'),
        ),
        migrations.AddField(
            model_name='book',
            name='more_infos',
            field=models.URLField(default='', verbose_name="Plus d'infos"),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Titre'),
        ),
    ]
