# Generated by Django 4.0.3 on 2022-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0007_alter_book_options_book_isbn_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='app_books.category'),
        ),
    ]
