# Generated by Django 4.0.3 on 2022-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0008_alter_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='current_pages',
            new_name='current_page',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ManyToManyField(to='app_books.book', verbose_name='Livre'),
        ),
    ]
