# Generated by Django 4.0.3 on 2022-07-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0009_rename_current_pages_book_current_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='couverture',
            field=models.URLField(default='', verbose_name='Couverture'),
        ),
    ]
