# Generated by Django 4.0.3 on 2022-08-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_books", "0010_alter_book_couverture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="contact",
            field=models.URLField(blank=True, default="", verbose_name="Contact"),
        ),
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=255, unique=True),
        ),
    ]
