name: CI Django Postgres Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: localhost
      SQL_DB: db_test
      SQL_PORT: 5432
      DJANGO_SECRET_KEY: test_key_django
    services:
      postgres_main:
        image: postgres:14
        env:
          SQL_USER: ${{ env.SQL_USER }}
          SQL_PASSWORD: ${{ env.SQL_PASSWORD }}
          SQL_DB: ${{ env.SQL_DB }}
        ports:
          - 5432:5432
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install -r requirements_dev.txt
      - name: Run Tests
        env:
          DEBUG: "0"
          DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
          DB_USERNAME: ${{ env.SQL_USER }}
          DB_PASSWORD: ${{ env.SQL_PASSWORD }}
          DB_HOST: ${{ env.SQL_HOST }}
          DB_DATABASE: ${{ env.SQL_DB }}
          DB_PORT: ${{ env.SQL_PORT }}
        run: |
          pytest